services:
  app:
    build: .
    image: nhmdenmark/dassco-file-proxy:1.3.0
    ports:
      - 8080:8080
    environment:
      CORS_ALLOW_ORIGIN: http://localhost:8080
      POSTGRES_URL: jdbc:postgresql://database:5432/dassco_file_proxy
      POSTGRES_USER: dassco_file_proxy
      POSTGRES_PASSWORD: dassco_file_proxy
      KEYCLOAK_REALM: dassco
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/
      KEYCLOAK_RESOURCE: dassco-asset-service
      ERDA_SERVER: io.erda.dk
      ERDA_PORT: 21
      ERDA_USER: christoffer@northtech.dk
      ERDA_PASSWORD: qLJqjEga8zpA
      SFTP_PRIVATE_KEY_LOCATION: /private_key
    volumes:
      - ./private_key:/private_key
