services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/data:/opt/keycloak/data:rw
      - ./keycloak/themes:/opt/keycloak/themes:rw
      - ./keycloak/certs:/opt/keycloak/certs:rw
    ports:
      - 8083:8080
      - 8444:8443
    command:
      - start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --https-certificate-file=/opt/keycloak/certs/server_keycloak_certificate.pem --https-certificate-key-file=/opt/keycloak/certs/server_keycloak_key.pem
