services:
  app:
    build: .
    image: nhmdenmark/dassco-file-proxy:2.0.0
    ports:
      - 8081:8080
    environment:
      #Allowing this will rewrite the environmental variable present in application.properties, making the documentation inaccessible (CORS error)
      #CORS_ALLOW_ORIGIN: http://localhost:8080
      POSTGRES_URL: jdbc:postgresql://database:5432/dassco_file_proxy
      POSTGRES_USER: dassco_file_proxy
      POSTGRES_PASSWORD: dassco_file_proxy
      KEYCLOAK_REALM: dassco
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/
      KEYCLOAK_RESOURCE: dassco-asset-service
      ERDA_SERVER: io.erda.dk
      ERDA_PORT: 21
      SFTP_USERNAME: LBBxERyQuN
      SFTP_PRIVATE_KEY_LOCATION: /private.pem
      SFTP_PRIVATE_KEY_PASSPHRASE: password
      ASSET_SERVICE_ROOT_URL: http://asset-service:8084
    volumes:
      - ./private.pem:/private.pem
